In [6]:
import numpy as np

In [27]:
inputs = [1, 2, 3, 5]

In [28]:
input_dim = inputs[-3]

In [29]:
input_dim

2

In [30]:
shape = (10, 3)

In [31]:
shape

(10, 3)

In [32]:
np.dot(inputs, [[1,1], [1,1], [1,1], [1,1]])

array([11, 11])

In [1]:
from tensorflow.keras.metrics import categorical_accuracy

In [3]:
y_true = [[0, 0, 1], [0, 1, 0]]
y_pred = [[0.1, 0.9, 0.8], [0.05, 0.95, 0]]
m = categorical_accuracy(y_true, y_pred)
print(m)

tf.Tensor([0. 1.], shape=(2,), dtype=float32)


In [5]:
m.numpy()

array([0., 1.], dtype=float32)

In [7]:
np.mean(m.numpy())

0.5