In [2]:
import numpy as np

ShouldCalculateSimpleNeuron

In [3]:
inputs = [1, 2, 3]

In [4]:
weight = [2.2, 3.3, 1.1]

In [5]:
np.dot(inputs, weight)

12.1

In [39]:
inputs = np.array( [1, 2, 3] )

In [48]:
weight = np.array( [[0.1, 0.4, 0.7], [0.2, 0.5, 0.8], [0.3, 0.6, 0.9]] )

In [49]:
weight

array([[0.1, 0.4, 0.7],
       [0.2, 0.5, 0.8],
       [0.3, 0.6, 0.9]])

In [50]:
inputs * weight

array([[0.1, 0.8, 2.1],
       [0.2, 1. , 2.4],
       [0.3, 1.2, 2.7]])

In [51]:
np.dot(inputs, weight)

array([1.4, 3.2, 5. ])